Course URL: https://www.youtube.com/watch?v=4c_mwnYdbhQ

# Data types

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
#access
print(a)
print(a[1])
print(a[:-2])

[1 2 3 4 5]
2
[1 2 3]


You can access a numpy array as a normal array.

In [3]:
a_mul_dim = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

b_mul_dim = np.array([[[1, 2, 3, 1],
                       [3, 4, 5, 1],
                       [7, 8, 9, 1]],
                      [[1, 1, 1, 1],
                       [1, 1, 1, 1],
                       [1, 1, 1, 1]]])

You can also initiate different types of numpy array

`a_mul_dim` is a 3 by 3 matrix.

and `b_mul_dim` is 2 3 by 4 matrices.

In [4]:
print(a_mul_dim[0])
print(a_mul_dim[0, 1])

[1 2 3]
2


In [5]:
#size of the matrix
print(a_mul_dim.shape)
#has to be homogeneous matrix to work
print(b_mul_dim.shape)

(3, 3)
(2, 3, 4)


In [6]:
#The depth of parenthesis
print(a_mul_dim.ndim)
print(b_mul_dim.ndim)

2
3


In [7]:
#The number of elements in the nparray
print(b_mul_dim.size)

24


In [8]:
#The data type
print(b_mul_dim.dtype)

int64


In [9]:
a_mul_dim = np.array([[1, 2, 3],
                      [4, 'Hello!', 6],
                      [7, 8, 9]])
print(a_mul_dim.dtype)

<U21


While doing this, the array turns into a string array, which changes all the data even number data into a string data type which is U21 meaning that it's contained with strings with less than 21 characters.

In [10]:
print(a_mul_dim[0][0].dtype)

<U1


The number is changed into a string.

In [11]:
c_mul_dim = np.array([[1, 2, 3],
                      [4, "5", 6],
                      [7, 8, 9]], dtype = np.float32)
print(c_mul_dim.dtype)
print(c_mul_dim[1][1].dtype)
print(c_mul_dim[0, 0].dtype)

float32
float32
float32


It will chagne all the data within it to one certain datatype

In [12]:
d = {'1': 'A'}
d_mul_dim = np.array([[1, 2, 3],
                      [4, d, 6],
                      [7, 8, "hello"]])
print(d_mul_dim.dtype)
print(type(d_mul_dim[1][0]))

object
<class 'int'>


Only if you do this, the np array will turn into a normal python object, which contains different data types.

# Filling arrays

In [14]:
a_fa = np.full((2, 3, 4), 9)
print(a_fa)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


Fills 2 matrices that are 3 by 4 with 9

In [15]:
b_fa = np.zeros((3, 3, 4))
print(b_fa)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


Fill with zero.

In [16]:
c_fa = np.ones((3, 3, 4))
print(c_fa)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


Fill with 1s

In [17]:
d_fa = np.empty((3, 3, 3))
print(d_fa)

[[[6.23042070e-307 2.78149850e-307 1.60220393e-306]
  [2.44776798e-307 1.69119330e-306 8.90104917e-307]
  [4.45058486e-308 7.56598449e-307 6.23054633e-307]]

 [[1.37962185e-306 1.37962456e-306 1.69119330e-306]
  [8.45593934e-307 9.34605716e-307 7.56593696e-307]
  [1.33511562e-306 1.60220528e-306 8.45596650e-307]]

 [[9.34608431e-307 9.34609790e-307 1.95812747e-306]
  [6.23060744e-307 6.23053954e-307 9.34609790e-307]
  [8.45593934e-307 9.34600963e-307 5.68175493e-322]]]


Declare without initiating.

In [18]:
x_values = np.arange(0, 1000 ,5)
print(x_values)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


from 0 to 1000, with a stepsize of 5

In [19]:
y_values = np.linspace(0, 1000, 5)
print(y_values)

[   0.  250.  500.  750. 1000.]


The third parameters is the number of elements you want to have.

# NaN & Inf

In [20]:
print(np.nan)
print(np.inf)

nan
inf


In [21]:
print(np.isnan(np.nan))
print(np.isinf(np.inf))

True
True


Check for NaN and Inf

In [22]:
print(np.isnan(np.sqrt(-1)))
print(np.array([10]) / 0)

True
[inf]


C:\Users\Administrator\AppData\Local\Temp\ipykernel_6152\655237797.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(-1)))
C:\Users\Administrator\AppData\Local\Temp\ipykernel_6152\655237797.py:2: RuntimeWarning: divide by zero encountered in divide
  print(np.array([10]) / 0)


#Mathematical Operations

In [23]:
l1 = [1, 2, 3, 4, 5]
l2 = [6, 7, 8, 9, 0]

a1 = np.array(l1)
a2 = np.array(l2)

print("Normal python list: ")
print(l1 * 5)
print("Numpy arrays: ")
print(a1 * 5)

Normal python list: 
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy arrays: 
[ 5 10 15 20 25]


The difference in multiplication.

In [24]:
print("Normal python list: ")
print(l1 + l2)
print("Numpy arrays: ")
print(a1 + a2)
print(a1 + 5)

Normal python list: 
[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
Numpy arrays: 
[ 7  9 11 13  5]
[ 6  7  8  9 10]


The difference in addition.

In [25]:
print(a1 * a2)
print(a1 / a2)
print(a1 - a2)

[ 6 14 24 36  0]
[0.16666667 0.28571429 0.375      0.44444444        inf]
[-5 -5 -5 -5  5]


C:\Users\Administrator\AppData\Local\Temp\ipykernel_6152\511581756.py:2: RuntimeWarning: divide by zero encountered in divide
  print(a1 / a2)


## Different Dimensions.

In [26]:
b1 = np.array([1, 2, 3])
b2 = np.array([[1],
               [2]])
print("Addition: ")
print(b1 + b2)
print("Multiplication: ")
print(b1 * b2)

Addition: 
[[2 3 4]
 [3 4 5]]
Multiplication: 
[[1 2 3]
 [2 4 6]]


Functions:

In [27]:
c1 = np.array([[1, 2, 3],
               [4, 5, 5]])

print(np.sqrt(c1))
print(np.sin(c1))
print(np.cos(c1))
print(np.tan(c1))
print(np.arctan(c1))
print(np.exp(c1))
print(np.log10(c1))
print(np.log2(c1))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.23606798]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.95892427]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.28366219]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -3.38051501]]
[[0.78539816 1.10714872 1.24904577]
 [1.32581766 1.37340077 1.37340077]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  148.4131591 ]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.69897   ]]
[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.32192809]]


# Array functions:

In [28]:
aa1 = np.array([1, 2, 3])

print(np.append(aa1, [7, 8, 9]))
print(aa1)

aa1 = np.append(aa1, [7, 8, 9])
print(aa1)

[1 2 3 7 8 9]
[1 2 3]
[1 2 3 7 8 9]


In [29]:
aa1 = np.insert(aa1, 3, [4, 5, 6])
print(aa1)

[1 2 3 4 5 6 7 8 9]


In [30]:
aa2 = np.array([[1, 2, 3],
                [4, 5, 6]])
print(np.delete(aa2, 2))
print(aa2)

[1 2 4 5 6]
[[1 2 3]
 [4 5 6]]


In [31]:
print(np.delete(aa2, 1, 0))
#1, means the index 1 row
#0 means to look at this matrix row-wise
print(np.delete(aa2, 0, 0))

[[1 2 3]]
[[4 5 6]]


In [32]:
print(np.delete(aa2, 1, 1))

[[1 3]
 [4 6]]


The delete function will either delete the row or column

# Strucuring Method

In [70]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

print(a.shape)
print(a.reshape((5, 4)))
print(a.reshape((20, )))
print(a.reshape((10, 2)))

(4, 5)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [53]:
print(a.reshape((2, 2, 5)))
print(a.reshape((5, 2, 2)))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


Note that this also have to be assigned.

In [71]:
print(a.shape)
a.reshape(10, 2)
print(a.shape)
a.resize(10, 2)
print(a.shape)

(4, 5)
(4, 5)
(10, 2)


In [72]:
a.resize(4, 5)
print(a.flatten())
print(a.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [73]:
var1 = a.flatten()
var1[2] = 100
print(var1)
print(a)

[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Didn't change the original

In [78]:
var2 = a.ravel()
var2[2] = 100
print(var2)
print(a)
var2[2] = 3

[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[  1   2 100   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


Changes the original one.

In [80]:
print(a)
var = [v for v in a.flat]
print(var)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20)]


In [81]:
print(a.transpose())
print(a.T)
print(a.swapaxes(0, 1))

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


## Joining and Spliting arrays

In [85]:
b = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]])
c = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

d = np.concatenate((b, c), axis = 0)
print(d)
d = np.concatenate((b, c), axis = 1)
print(d)
d = np.stack((b, c))
print(d)
d = np.vstack((b, c))
print(d)
d = np.hstack((b, c))
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


Stack adds a dimension to it.

vstack is vertical stack, and hstack is horizontal stack.

In [87]:
e = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

print(np.split(e, 2, axis = 0))
print(np.split(e, 5, axis = 1))

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]
[array([[ 1],
       [ 6],
       [11],
       [16]]), array([[ 2],
       [ 7],
       [12],
       [17]]), array([[ 3],
       [ 8],
       [13],
       [18]]), array([[ 4],
       [ 9],
       [14],
       [19]]), array([[ 5],
       [10],
       [15],
       [20]])]


In [88]:
print(e.min())
print(e.max())
print(e.mean())
print(e.std())
print(e.sum())
print(np.median(e))

1
20
10.5
5.766281297335398
210
10.5


# Random Values

In [91]:
number = np.random.randint(100)
print(number)

48


In [95]:
numbers1 = np.random.randint(0, 1, size = (2, 3, 4))
print(numbers1)
numbers2 = np.random.randint(1, 10, size = (2, 3, 4))
print(number2)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[[4 8 9 3]
  [7 4 1 6]
  [4 6 2 6]]

 [[8 4 4 1]
  [8 9 3 1]
  [8 6 3 4]]]


In [96]:
numbers3 = np.random.binomial(10, p = 0.5, size = (5, 10))
print(numbers3)

[[5 5 6 5 5 5 6 6 7 7]
 [7 6 7 2 6 7 5 5 6 4]
 [6 6 7 6 6 5 6 2 3 3]
 [7 3 4 5 4 5 7 5 7 2]
 [7 6 4 4 6 5 7 5 3 3]]


In [98]:
numbers4 = np.random.normal(loc = 170, scale = 15, size = (5, 10))
print(numbers4)

[[168.06894663 167.47754014 155.71710482 179.36179674 151.74591578
  190.93712389 163.26492831 163.27676302 177.16316211 196.86882373]
 [192.74416749 173.19564962 161.60324257 165.28717666 159.7472113
  143.48761032 151.28610934 151.19128036 185.30487819 125.41997391]
 [156.60479931 169.47329038 184.78690969 169.195688   143.03043671
  169.90614892 180.66182574 182.19986853 148.41539788 176.23116996]
 [166.91792323 169.46636937 167.32937998 191.00607144 177.50129459
  167.7620205  177.00838074 164.32038454 162.57925589 187.33639854]
 [199.34211442 173.33611725 138.44611145 183.58556478 150.44762346
  158.2527678  170.24061091 169.46730427 157.31508997 173.73504848]]


In [99]:
numbers5 = np.random.choice([10, 20, 30, 40, 50], size = (5, 10))
print(numbers5)

[[40 20 20 50 10 20 30 40 50 30]
 [20 50 20 20 30 30 30 40 50 20]
 [30 50 30 10 40 30 10 20 40 30]
 [20 10 10 20 30 40 30 30 20 50]
 [30 20 50 30 20 20 50 10 20 50]]


# Exporting and Inporting numpy arrays

In [103]:
f = np.array([[1, 2, 3, 4, 5, 6],
              [7, 8, 9, 10, 11, 12],
              [13, 14, 15, 16, 17, 18],
              [19, 20, 21, 22, 23, 24]])

np.save("Numpy test exporting file", a)
np.savetxt("Numpy test exporting file.csv", a, delimiter = ",")

In [104]:
g = np.load("Numpy test exporting file.npy")
h = np.loadtxt("Numpy test exporting file.csv", delimiter = ",")
print(g)
print(h)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]
